
import java.util.List;
import java.awt.Panel;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.Comparator;
import java.util.logging.Level;
import java.util.logging.Logger;




public class QuanLySV extends javax.swing.JFrame {
 private List<Student> list=new ArrayList<>();
 private DefaultTableModel model1=new DefaultTableModel();
    public QuanLySV() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        BangSV = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ten = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        gioitinh = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nganh = new javax.swing.JTextField();
        ThemSV = new javax.swing.JButton();
        SuaSV = new javax.swing.JButton();
        ma = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ngaysinh = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ngaynhaphc = new com.toedter.calendar.JDateChooser();
        XoaSV = new javax.swing.JButton();
        Luudulieu = new javax.swing.JButton();
        DocDuLieu = new javax.swing.JButton();
        SXtheoten = new javax.swing.JButton();
        SXtheongaysinh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QuanLySV");
        setBackground(new java.awt.Color(255, 0, 0));

        BangSV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ma SV", "Ho ten", "Gioi tinh", "Ngay sinh", "Nganh", "Ngay nhap hoc"
            }
        ));
        BangSV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BangSVMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(BangSV);

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Ho ten SV :");

        ten.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        ten.setToolTipText("");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Gioi tinh :");

        gioitinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam\t", "Nu" }));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("QUAN LY THONG TIN SINH VIEN");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Nganh :");

        ThemSV.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ThemSV.setForeground(new java.awt.Color(204, 0, 0));
        ThemSV.setText("Them SV");
        ThemSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThemSVActionPerformed(evt);
            }
        });

        SuaSV.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        SuaSV.setForeground(new java.awt.Color(204, 0, 0));
        SuaSV.setText("Sua SV");
        SuaSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SuaSVActionPerformed(evt);
            }
        });

        ma.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ma.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Ma SV :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Ngay sinh :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Ngay nhap hoc :");

        XoaSV.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        XoaSV.setForeground(new java.awt.Color(204, 0, 0));
        XoaSV.setText("Xoa SV");
        XoaSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XoaSVActionPerformed(evt);
            }
        });

        Luudulieu.setText("Luu du lieu");
        Luudulieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LuudulieuActionPerformed(evt);
            }
        });

        DocDuLieu.setText("Doc du lieu");
        DocDuLieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DocDuLieuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 808, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ten)
                                    .addComponent(gioitinh, 0, 201, Short.MAX_VALUE)
                                    .addComponent(nganh))
                                .addGap(76, 76, 76)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel6)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(ThemSV, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(107, 107, 107)
                        .addComponent(SuaSV, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ngaysinh, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ngaynhaphc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                            .addComponent(ma, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(XoaSV)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(Luudulieu, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112)
                .addComponent(DocDuLieu, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel4, jLabel6});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel3, jLabel7});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {SuaSV, ThemSV, XoaSV});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {ma, ngaynhaphc, ngaysinh});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel7)))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gioitinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nganh)
                            .addComponent(jLabel5)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(ngaynhaphc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ThemSV, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SuaSV, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(XoaSV))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Luudulieu, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(DocDuLieu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel3, jLabel5, jLabel7});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jLabel4, jLabel6});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {SuaSV, ThemSV, XoaSV});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {ma, ngaynhaphc, ngaysinh});

        SXtheoten.setBackground(new java.awt.Color(204, 0, 0));
        SXtheoten.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        SXtheoten.setText("Sap xep theo ten");
        SXtheoten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SXtheotenActionPerformed(evt);
            }
        });

        SXtheongaysinh.setBackground(new java.awt.Color(255, 0, 0));
        SXtheongaysinh.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        SXtheongaysinh.setText("Sap xep theo ngay sinh");
        SXtheongaysinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SXtheongaysinhActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(SXtheoten, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119)
                .addComponent(SXtheongaysinh)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {SXtheongaysinh, SXtheoten});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SXtheoten)
                    .addComponent(SXtheongaysinh))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {SXtheongaysinh, SXtheoten});

        pack();
    }// </editor-fold>//GEN-END:initComponents
     public void fillToTable(){
         SimpleDateFormat df= new SimpleDateFormat ("dd-MM-yyyy", Locale.ENGLISH);
         model1=(DefaultTableModel) BangSV.getModel();
         model1.setRowCount(0);
         for (Student obj : list) {
            Object[] row =new Object[]{
             obj.getStudentID(),obj.getName(),obj.getGender(),df.format(obj.getBirthday()),obj.getMajor(),
            df.format(obj.getEnrolledDate())};
        model1.addRow(row);
     }
     }
     public void addStudent(){
         Student s=new Student();
         s.setStudentID(ma.getText());
         s.setName(ten.getText().trim());
         s.setGender(gioitinh.getSelectedItem().toString());
         s.setBirthday(ngaysinh.getDate());
         s.setMajor(nganh.getText());
         s.setEnrolledDate(ngaynhaphc.getDate());
         list.add(s);
         
     }
    public void getDataFromTable(){
        int i= BangSV.getSelectedRow();
        Student s=list.get(i);
        ma.setText(s.getStudentID().toString());
        ten.setText(s.getName().toString());
        gioitinh.setSelectedItem(s.getGender());
         ngaysinh.setDate(s.getBirthday());
         nganh.setText(s.getMajor());
         ngaynhaphc.setDate(s.getEnrolledDate());
        
    }
    private void ThemSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThemSVActionPerformed
//
//        Student obj = new Student(ma.getText(),
//                            nganh.getText(),
//                            ngaynhaphc.getDate(),
//                            ten.getText(),
//                            ngaysinh.getDate(), 
//                            gioitinh.getSelectedItem().toString());
//        
//        DefaultTableModel model1=(DefaultTableModel) BangSV.getModel();
//        SimpleDateFormat df= new SimpleDateFormat ("dd-MM-yyyy", Locale.ENGLISH);
//        if (ma.getText().equals("") ||ten.getText().equals(""))
//        {
//            JOptionPane.showMessageDialog(new Panel(), "LOI NHAP THONG TIN", "THONG BAO ",
//							JOptionPane.ERROR_MESSAGE);
//        }
//        else{
//        model1.insertRow(model1.getRowCount(),new Object[]{ 
//            obj.getStudentID(),obj.getName(),obj.getGender(),df.format(obj.getBirthday()),obj.getMajor(),
//            df.format(obj.getEnrolledDate())
//        });
//                ma.setText("");
//                ten.setText("");
//                gioitinh.setToolTipText("");
//                 Date date = null;
//                ngaysinh.setDate(date);
//                nganh.setText("");
//                ngaynhaphc.setDate(date);
//        }      
          addStudent();
          
              ma.setText("");
                ten.setText("");
                gioitinh.setToolTipText("");
                 
                ngaysinh.setDate(null);
                nganh.setText("");
                ngaynhaphc.setDate(null);
          fillToTable();
    }//GEN-LAST:event_ThemSVActionPerformed

    private void SuaSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SuaSVActionPerformed
        int i=BangSV.getSelectedRow();
        DefaultTableModel model1=(DefaultTableModel) BangSV.getModel();
         SimpleDateFormat df= new SimpleDateFormat ("dd-MM-yyyy", Locale.ENGLISH);
        if (i>=0)
        {
            int output =JOptionPane.showConfirmDialog(new Panel(), "BAN CHAC CHAN MUON SUA KHONG ?",
							" THONG BAO XAC NHAN", JOptionPane.YES_NO_OPTION);
            if (output ==JOptionPane.YES_OPTION)
            {
                model1.setValueAt(ma.getText(), i, 0);
                model1.setValueAt(ten.getText(), i, 1);
                model1.setValueAt(gioitinh.getSelectedItem().toString(), i, 2);
                model1.setValueAt(df.format(ngaysinh.getDate()), i, 3);
                model1.setValueAt(nganh.getText(), i, 4);
                model1.setValueAt(df.format(ngaynhaphc.getDate()), i, 5);
                 ma.setText("");
                ten.setText("");
                gioitinh.setToolTipText("");
                 Date date = null;
                ngaysinh.setDate(date);
                nganh.setText("");
                ngaynhaphc.setDate(date);    
            }
        }
        else
            {
	JOptionPane.showMessageDialog(new Panel(), 
                                        "LOI !!!",
                                        "THONG BAO ", 
                                        JOptionPane.ERROR_MESSAGE);
	   }
//         fillTable();
    }//GEN-LAST:event_SuaSVActionPerformed

    private void XoaSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XoaSVActionPerformed
        int s = BangSV.getSelectedRow();
        DefaultTableModel model1=(DefaultTableModel) BangSV.getModel();
	if (s >= 0) {
	int output = JOptionPane.showConfirmDialog(new Panel(),
                                                " BAN CHAC CHAN MUON XOA",
						" THONG BAO XAC NHAN", 
                                                JOptionPane.YES_NO_OPTION);
        if (output == JOptionPane.YES_OPTION) {
//		model1.removeRow(s);
//		for (int i = 0; i < BangSV.getRowCount(); i++) {
//		     BangSV.setValueAt(i + 1, i, 0);
//			}
                {
                    list.remove(s);
                    fillToTable();
                }
        }
        else {
		JOptionPane.showMessageDialog(new Panel(), "Loi !!!",
			"THONG BAO ", JOptionPane.ERROR_MESSAGE);
        }
        }
    }//GEN-LAST:event_XoaSVActionPerformed

    private void SXtheotenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SXtheotenActionPerformed
       
//       Collections.sort(list, new Comparator<Student>() {           
//           public int compare(Student o1,Student o2){
//               return o1.getName().compareTo(o2.getName());
//           }
//       });
//       fillTable();
      
//       fillTable();
      Comparator<Student> comparator =new Comparator<Student>() {
          @Override
          public int compare(Student o1, Student o2) {
              String n1=o1.name;
              String n2=o2.name;
             return n1.compareTo(n2);
      }   
      };
      Collections.sort(list,comparator);
      fillToTable();
     
    
    }//GEN-LAST:event_SXtheotenActionPerformed


    private void SXtheongaysinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SXtheongaysinhActionPerformed
//     Collections.sort(list, (Student o1, Student o2) -> o1.getBirthday().compareTo(o2.getBirthday()));
////      fillTable();
       Collections.sort(list, new Comparator<Student>() {
           
           public int compare(Student o1,Student o2){
               return o1.getBirthday().compareTo(o2.getBirthday());
           }
       });
      fillToTable();
    }//GEN-LAST:event_SXtheongaysinhActionPerformed

    private void BangSVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BangSVMouseClicked
           DefaultTableModel model1=(DefaultTableModel) BangSV.getModel();
        int i = BangSV.getSelectedRow();
        				ma.setText(model1.getValueAt(i, 0).toString());
				ten.setText(model1.getValueAt(i, 1).toString());
				gioitinh.setToolTipText(model1.getValueAt(i, 2).toString());
				//ngaysinh.setDateFormatString(model1.getValueAt(i, 4).toString());
                                ngaysinh.setDateFormatString(model1.getValueAt(i, 3).toString());
				nganh.setText(model1.getValueAt(i, 4).toString());
				ngaynhaphc.setDateFormatString( model1.getValueAt(i, 5).toString());
//            getDataFromTable();
    }//GEN-LAST:event_BangSVMouseClicked

    private void DocDuLieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DocDuLieuActionPerformed
     try {
         FileInputStream fi = new FileInputStream("d:/ThongTinSinhVien.txt");
         ObjectInputStream ois = new ObjectInputStream(fi);
         DefaultTableModel model1=  (DefaultTableModel) ois.readObject();
     } catch (FileNotFoundException ex) {
         Logger.getLogger(QuanLySV.class.getName()).log(Level.SEVERE, null, ex);
     } catch (IOException | ClassNotFoundException ex) {
         Logger.getLogger(QuanLySV.class.getName()).log(Level.SEVERE, null, ex);
     }
    }//GEN-LAST:event_DocDuLieuActionPerformed

    private void LuudulieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LuudulieuActionPerformed
        DefaultTableModel model1=(DefaultTableModel) BangSV.getModel();
     try {
         FileOutputStream fo = new FileOutputStream("d:/ThongTinSinhVien.txt");
         ObjectOutputStream oos= new ObjectOutputStream(fo);
         oos.writeObject(model1);
         fo.close();
         oos.close();
         
     } catch (FileNotFoundException ex) {
       
     } catch (IOException ex) {
         Logger.getLogger(QuanLySV.class.getName()).log(Level.SEVERE, null, ex);
     }
    }//GEN-LAST:event_LuudulieuActionPerformed
   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLySV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLySV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLySV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLySV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLySV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable BangSV;
    private javax.swing.JButton DocDuLieu;
    private javax.swing.JButton Luudulieu;
    private javax.swing.JButton SXtheongaysinh;
    private javax.swing.JButton SXtheoten;
    private javax.swing.JButton SuaSV;
    private javax.swing.JButton ThemSV;
    private javax.swing.JButton XoaSV;
    private javax.swing.JComboBox<String> gioitinh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField ma;
    private javax.swing.JTextField nganh;
    private com.toedter.calendar.JDateChooser ngaynhaphc;
    private com.toedter.calendar.JDateChooser ngaysinh;
    private javax.swing.JTextField ten;
    // End of variables declaration//GEN-END:variables


  
}
